### PR TITLE
Added five new applications.

### PR DESCRIPTION
**Pull request by comicallycluttered**
Added nomacs, PhotoQt, SMPlayer, qimgv, and Vorta.

Also edited the description for Muon, since it's a GUI front-end for APT, so it's only available on Debian and Ubuntu derivatives.

Quick note about a couple of the apps:

nomacs was unmaintained for quite a while and only recently began activity again, so I don't really know when they'll push the next release. Website is unmaintained, so linked to their repo instead. Feel free not to add it if you feel like it's outdated or and/or unstable.

qimgv is a special case. The developer lives in Ukraine, and development has been put on hold indefinitely for obvious reasons. However, the dev branch is still active (as of yesterday, at least), but I don't know when or if those changes will be pushed to main any time soon. Totally understandable if you'd prefer not to add this to the list right now.

### CODE REVIEW

**Comment by ghost** [comment]
I prefer to list as many applications as possible, even if they are not in active development. Only when they're considered "outdated" or "unstable" (e.g. built with deprecated Qt versions) I'll remove them.


Nice additions. I'm currently in the middle of organizing everything into new categories, you'll most likely need to commit a change (once I push) to avoid conflicts.

**Comment by comicallycluttered** [comment]
No problem! Thanks for the response.

I'll definitely make sure to check in and make the changes when you've sorted the categories and all out.

**Comment by ghost** [comment]
The updated categories have been merged. Can you commit a change?

**Comment by comicallycluttered** [comment]
Made the changes. Sorry about all the commits, still need to get used to GitHub.

**Comment by ghost** [comment]
That's alright, thanks for the submission!

**Pull request merged**
