### PR TITLE
Added some more apps

### PR DESCRIPTION
**Pull request by superjaded**
Added JetBrains Toolbox under Development
Added ProtonUp-Qt under Games
Added mpc-qt under Multimedia
Added Barrier under Utilities

### CODE REVIEW

**Comment by ghost** [comment]
Looks good, I'm going to hold off on merges until I get the new categories set up. Should be done by today.

**Comment by ghost** [comment]
I have updated the categories, can you commit a change?

**Comment by superjaded** [comment]
I believe the conflicts should be resolved now, but let me know if you see any lingering issues.

**Comment by ghost** [comment]
I would say add #Independent to apps that aren't created by or following the HIG of some ecosystem. Maybe Jetbrains Toolbox should be in the "Integrated Development Environment" section?


I may just merge "Integrated Development Environment" with "Development" now that I think about it. So just add the appropriate tags and it'll be good to go.

Thanks.

**Comment by superjaded** [comment]
Sounds good. I'll add the tags in a bit. 

Didn't even notice the IDE section when I was going through them earlier. It's kind of hard to categorize JetBrains Toolbox since it's neither a development tool or an IDE on its own. It's essentially a downloader (and updater, I guess) for other JetBrains products, so there may be an argument for slapping it in Misc instead of either Development or IDE. I think that's what I'll do with it.

**Comment by ghost** [comment]
Nice! I agree, the categories are a little ambiguous. Since the toolbox manages IDEs, I think we picked the right category.

**Pull request merged**
